# version: "3.6"
services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: workplacify_db
  workplacify:
    image: workplacify:1.0.0
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  default:
    name: workplacify-network
    